In [1]:
#Data handling Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#ML pacakges
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [3]:
churn=pd.read_csv('churn.csv')

In [4]:
col_names=churn.columns.tolist()
print('Column Names:')
print(col_names)

Column Names:
['State', 'Account Length', 'Area Code', 'Phone', "Int'l Plan", 'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls', 'Day Charge', 'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins', 'Night Calls', 'Night Charge', 'Intl Mins', 'Intl Calls', 'Intl Charge', 'CustServ Calls', 'Churn?']


In [5]:
churn.head(5)

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   
3    OH              84        408  375-9999        yes         no   
4    OK              75        415  330-6626        yes         no   

   VMail Message  Day Mins  Day Calls  Day Charge  ...  Eve Calls  Eve Charge  \
0             25     265.1        110       45.07  ...         99       16.78   
1             26     161.6        123       27.47  ...        103       16.62   
2              0     243.4        114       41.38  ...        110       10.30   
3              0     299.4         71       50.90  ...         88        5.26   
4              0     166.7        113       28.34  ...        122       12.61   

   Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0       244.7           91         11.01       10.0           3         2.70   
1       254.4          103         11.45       13.7           3         3.70   
2       162.6          104          7.32       12.2           5         3.29   
3       196.9           89          8.86        6.6           7         1.78   
4       186.9          121          8.41       10.1           3         2.73   

   CustServ Calls  Churn?  
0               1  False.  
1               1  False.  
2               0  False.  
3               2  False.  
4               3  False.  

[5 rows x 21 columns]

In [6]:
 churn['CustServ Calls'].max()

9

In [7]:
churn_result=churn['Churn?']#islolate target data
y=np.where(churn_result=='True.',1,0)
y

array([0, 0, 0, ..., 0, 0, 0])

In [8]:
np.unique(y)

array([0, 1])

In [9]:
y[0:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [10]:
#We don't these columns
to_drop=['State','Area Code','Phone','Churn?']
churn_feat_space=churn.drop(to_drop,axis=1)
to_drop

['State', 'Area Code', 'Phone', 'Churn?']

In [11]:
churn_feat_space

Account Length Int'l Plan VMail Plan  VMail Message  Day Mins  \
0                128         no        yes             25     265.1   
1                107         no        yes             26     161.6   
2                137         no         no              0     243.4   
3                 84        yes         no              0     299.4   
4                 75        yes         no              0     166.7   
...              ...        ...        ...            ...       ...   
3328             192         no        yes             36     156.2   
3329              68         no         no              0     231.1   
3330              28         no         no              0     180.8   
3331             184        yes         no              0     213.8   
3332              74         no        yes             25     234.4   

      Day Calls  Day Charge  Eve Mins  Eve Calls  Eve Charge  Night Mins  \
0           110       45.07     197.4         99       16.78       244.7   
1           123       27.47     195.5        103       16.62       254.4   
2           114       41.38     121.2        110       10.30       162.6   
3            71       50.90      61.9         88        5.26       196.9   
4           113       28.34     148.3        122       12.61       186.9   
...         ...         ...       ...        ...         ...         ...   
3328         77       26.55     215.5        126       18.32       279.1   
3329         57       39.29     153.4         55       13.04       191.3   
3330        109       30.74     288.8         58       24.55       191.9   
3331        105       36.35     159.6         84       13.57       139.2   
3332        113       39.85     265.9         82       22.60       241.4   

      Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0              91         11.01       10.0           3         2.70   
1             103         11.45       13.7           3         3.70   
2             104          7.32       12.2           5         3.29   
3              89          8.86        6.6           7         1.78   
4             121          8.41       10.1           3         2.73   
...           ...           ...        ...         ...          ...   
3328           83         12.56        9.9           6         2.67   
3329          123          8.61        9.6           4         2.59   
3330           91          8.64       14.1           6         3.81   
3331          137          6.26        5.0          10         1.35   
3332           77         10.86       13.7           4         3.70   

      CustServ Calls  
0                  1  
1                  1  
2                  0  
3                  2  
4                  3  
...              ...  
3328               2  
3329               3  
3330               2  
3331               2  
3332               0  

[3333 rows x 17 columns]

In [12]:
#converting yes/no to boolean values
yes_no_cols=["Int'l Plan","VMail Plan"]
churn_feat_space[yes_no_cols]=churn_feat_space[yes_no_cols]=='yes'
churn_feat_space

Account Length  Int'l Plan  VMail Plan  VMail Message  Day Mins  \
0                128       False        True             25     265.1   
1                107       False        True             26     161.6   
2                137       False       False              0     243.4   
3                 84        True       False              0     299.4   
4                 75        True       False              0     166.7   
...              ...         ...         ...            ...       ...   
3328             192       False        True             36     156.2   
3329              68       False       False              0     231.1   
3330              28       False       False              0     180.8   
3331             184        True       False              0     213.8   
3332              74       False        True             25     234.4   

      Day Calls  Day Charge  Eve Mins  Eve Calls  Eve Charge  Night Mins  \
0           110       45.07     197.4         99       16.78       244.7   
1           123       27.47     195.5        103       16.62       254.4   
2           114       41.38     121.2        110       10.30       162.6   
3            71       50.90      61.9         88        5.26       196.9   
4           113       28.34     148.3        122       12.61       186.9   
...         ...         ...       ...        ...         ...         ...   
3328         77       26.55     215.5        126       18.32       279.1   
3329         57       39.29     153.4         55       13.04       191.3   
3330        109       30.74     288.8         58       24.55       191.9   
3331        105       36.35     159.6         84       13.57       139.2   
3332        113       39.85     265.9         82       22.60       241.4   

      Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0              91         11.01       10.0           3         2.70   
1             103         11.45       13.7           3         3.70   
2             104          7.32       12.2           5         3.29   
3              89          8.86        6.6           7         1.78   
4             121          8.41       10.1           3         2.73   
...           ...           ...        ...         ...          ...   
3328           83         12.56        9.9           6         2.67   
3329          123          8.61        9.6           4         2.59   
3330           91          8.64       14.1           6         3.81   
3331          137          6.26        5.0          10         1.35   
3332           77         10.86       13.7           4         3.70   

      CustServ Calls  
0                  1  
1                  1  
2                  0  
3                  2  
4                  3  
...              ...  
3328               2  
3329               3  
3330               2  
3331               2  
3332               0  

[3333 rows x 17 columns]

In [13]:
#Pull out features for future use
features=churn_feat_space.columns
print(features)

Index(['Account Length', 'Int'l Plan', 'VMail Plan', 'VMail Message',
       'Day Mins', 'Day Calls', 'Day Charge', 'Eve Mins', 'Eve Calls',
       'Eve Charge', 'Night Mins', 'Night Calls', 'Night Charge', 'Intl Mins',
       'Intl Calls', 'Intl Charge', 'CustServ Calls'],
      dtype='object')


In [14]:
churn_feat_space['VMail Plan'].value_counts()

False    2411
True      922
Name: VMail Plan, dtype: int64

In [15]:
x=churn_feat_space.astype(np.float)
x

Account Length  Int'l Plan  VMail Plan  VMail Message  Day Mins  \
0              128.0         0.0         1.0           25.0     265.1   
1              107.0         0.0         1.0           26.0     161.6   
2              137.0         0.0         0.0            0.0     243.4   
3               84.0         1.0         0.0            0.0     299.4   
4               75.0         1.0         0.0            0.0     166.7   
...              ...         ...         ...            ...       ...   
3328           192.0         0.0         1.0           36.0     156.2   
3329            68.0         0.0         0.0            0.0     231.1   
3330            28.0         0.0         0.0            0.0     180.8   
3331           184.0         1.0         0.0            0.0     213.8   
3332            74.0         0.0         1.0           25.0     234.4   

      Day Calls  Day Charge  Eve Mins  Eve Calls  Eve Charge  Night Mins  \
0         110.0       45.07     197.4       99.0       16.78       244.7   
1         123.0       27.47     195.5      103.0       16.62       254.4   
2         114.0       41.38     121.2      110.0       10.30       162.6   
3          71.0       50.90      61.9       88.0        5.26       196.9   
4         113.0       28.34     148.3      122.0       12.61       186.9   
...         ...         ...       ...        ...         ...         ...   
3328       77.0       26.55     215.5      126.0       18.32       279.1   
3329       57.0       39.29     153.4       55.0       13.04       191.3   
3330      109.0       30.74     288.8       58.0       24.55       191.9   
3331      105.0       36.35     159.6       84.0       13.57       139.2   
3332      113.0       39.85     265.9       82.0       22.60       241.4   

      Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0            91.0         11.01       10.0         3.0         2.70   
1           103.0         11.45       13.7         3.0         3.70   
2           104.0          7.32       12.2         5.0         3.29   
3            89.0          8.86        6.6         7.0         1.78   
4           121.0          8.41       10.1         3.0         2.73   
...           ...           ...        ...         ...          ...   
3328         83.0         12.56        9.9         6.0         2.67   
3329        123.0          8.61        9.6         4.0         2.59   
3330         91.0          8.64       14.1         6.0         3.81   
3331        137.0          6.26        5.0        10.0         1.35   
3332         77.0         10.86       13.7         4.0         3.70   

      CustServ Calls  
0                1.0  
1                1.0  
2                0.0  
3                2.0  
4                3.0  
...              ...  
3328             2.0  
3329             3.0  
3330             2.0  
3331             2.0  
3332             0.0  

[3333 rows x 17 columns]

In [16]:
#This is important
scaler=StandardScaler()
x=scaler.fit_transform(x)
x

array([[ 0.67648946, -0.32758048,  1.6170861 , ..., -0.60119509,
        -0.0856905 , -0.42793202],
       [ 0.14906505, -0.32758048,  1.6170861 , ..., -0.60119509,
         1.2411686 , -0.42793202],
       [ 0.9025285 , -0.32758048, -0.61839626, ...,  0.21153386,
         0.69715637, -1.1882185 ],
       ...,
       [-1.83505538, -0.32758048, -0.61839626, ...,  0.61789834,
         1.3871231 ,  0.33235445],
       [ 2.08295458,  3.05268496, -0.61839626, ...,  2.24335625,
        -1.87695028,  0.33235445],
       [-0.67974475, -0.32758048,  1.6170861 , ..., -0.19483061,
         1.2411686 , -1.1882185 ]])

In [17]:
f=pd.DataFrame(x)

In [18]:
f

0         1         2         3         4         5         6  \
0     0.676489 -0.327580  1.617086  1.234883  1.566767  0.476643  1.567036   
1     0.149065 -0.327580  1.617086  1.307948 -0.333738  1.124503 -0.334013   
2     0.902529 -0.327580 -0.618396 -0.591760  1.168304  0.675985  1.168464   
3    -0.428590  3.052685 -0.618396 -0.591760  2.196596 -1.466936  2.196759   
4    -0.654629  3.052685 -0.618396 -0.591760 -0.240090  0.626149 -0.240041   
...        ...       ...       ...       ...       ...       ...       ...   
3328  2.283878 -0.327580  1.617086  2.038605 -0.432895 -1.167924 -0.433386   
3329 -0.830437 -0.327580 -0.618396 -0.591760  0.942447 -2.164631  0.942714   
3330 -1.835055 -0.327580 -0.618396 -0.591760  0.018820  0.426808  0.019193   
3331  2.082955  3.052685 -0.618396 -0.591760  0.624778  0.227466  0.625153   
3332 -0.679745 -0.327580  1.617086  1.234883  1.003042  0.626149  1.003202   

             7         8         9        10        11        12        13  \
0    -0.070610 -0.055940 -0.070427  0.866743 -0.465494  0.866029 -0.085008   
1    -0.108080  0.144867 -0.107549  1.058571  0.147825  1.059390  1.240482   
2    -1.573383  0.496279 -1.573900 -0.756869  0.198935 -0.755571  0.703121   
3    -2.742865 -0.608159 -2.743268 -0.078551 -0.567714 -0.078806 -1.303026   
4    -1.038932  1.098699 -1.037939 -0.276311  1.067803 -0.276562 -0.049184   
...        ...       ...       ...       ...       ...       ...       ...   
3328  0.286348  1.299506  0.286880  1.547039 -0.874374  1.547188 -0.120832   
3329 -0.938353 -2.264816 -0.938172 -0.189297  1.170023 -0.188670 -0.228304   
3330  1.731930 -2.114211  1.732349 -0.177431 -0.465494 -0.175486  1.383778   
3331 -0.816080 -0.808966 -0.815203 -1.219628  1.885562 -1.221396 -1.876211   
3332  1.280309 -0.909370  1.279915  0.801482 -1.181033  0.800110  1.240482   

            14        15        16  
0    -0.601195 -0.085690 -0.427932  
1    -0.601195  1.241169 -0.427932  
2     0.211534  0.697156 -1.188218  
3     1.024263 -1.306401  0.332354  
4    -0.601195 -0.045885  1.092641  
...        ...       ...       ...  
3328  0.617898 -0.125496  0.332354  
3329 -0.194831 -0.231645  1.092641  
3330  0.617898  1.387123  0.332354  
3331  2.243356 -1.876950  0.332354  
3332 -0.194831  1.241169 -1.188218  

[3333 rows x 17 columns]

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [20]:
f.shape

(3333, 17)

# Logistic Regression

In [21]:
from sklearn.linear_model import LogisticRegression
#Initialize the classifier
print("Logistic Regression:")

model_LR=LogisticRegression()
#fit the model

model_LR.fit(x_train,y_train)


Logistic Regression:


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [22]:
np.unique(y_train)

array([0, 1])

In [24]:
#predict with test data
y_pred=model_LR.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 1])

In [27]:
#check accuracy
#numpy interepretes Treu and False as 1 and 0
LR_Accuracy=np.mean(y_test==y_pred)
LR_Accuracy

0.8636363636363636

In [29]:
#confusion Matrix
from sklearn.metrics import confusion_matrix
print("Logistic Regeression")
confusion_matrix(y_test,y_pred)

Logistic Regeression


array([[915,  25],
       [125,  35]], dtype=int64)

# Random Forest

In [30]:
from sklearn.ensemble import RandomForestClassifier
#initializ the classifier
print("Random Forest:")
model_RF=RandomForestClassifier()
#fit the model
model_RF.fit(x_train,y_train)

Random Forest:


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [32]:
#predict the dataset
y_pred=model_RF.predict(x_test)
y_pred

array([0, 0, 1, ..., 0, 1, 0])

In [33]:
#check accuracy
#numpy interepretes Treu and False as 1 and 0
RF_Accuracy=np.mean(y_test==y_pred)
RF_Accuracy

0.9390909090909091

In [34]:
#confusion Matrix
from sklearn.metrics import confusion_matrix
print("Random Forest")
confusion_matrix(y_test,y_pred)


Random Forest


array([[929,  11],
       [ 56, 104]], dtype=int64)

# Gradient Boosting

In [37]:
#Gradient Boosting
from sklearn.ensemble import GradientBoostingClassifier
#start modelling
model_GBC=GradientBoostingClassifier()
#fit the model
model_GBC.fit(x_train,y_train)    

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [39]:
#Predict with test data
y_pred=model_GBC.predict(x_test)
y_pred

array([0, 0, 1, ..., 0, 1, 0])

In [40]:
#check accuracy
#numpy interepretes Treu and False as 1 and 0
GB_Accuracy=np.mean(y_test==y_pred)
GB_Accuracy

0.9490909090909091

In [41]:
#confusion Matrix
from sklearn.metrics import confusion_matrix
print("Gradient Boostingt")
confusion_matrix(y_test,y_pred)


Gradient Boostingt


array([[932,   8],
       [ 48, 112]], dtype=int64)

# KNearest Neighbors

In [47]:
from sklearn import neighbors
#start modelling
model_KNN=neighbors.KNeighborsClassifier()
#fit the model
model_KNN.fit(x_train,y_train)  

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [48]:
#Predict with test data
y_pred=model_KNN.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 1, 0])

In [49]:
#check accuracy
#numpy interepretes Treu and False as 1 and 0
KNN_Accuracy=np.mean(y_test==y_pred)
KNN_Accuracy

0.889090909090909

In [50]:
#confusion Matrix
from sklearn.metrics import confusion_matrix
print("KNearest Neighbors")
confusion_matrix(y_test,y_pred)


KNearest Neighbors


array([[928,  12],
       [110,  50]], dtype=int64)

In [51]:
y_pred==y_test

array([ True,  True, False, ...,  True,  True,  True])

In [52]:
#Comparison
print('Gradient Boosting :',GB_Accuracy,'\n')
print('Logistic Regression :',LR_Accuracy,'\n')
print('Random Forest :',RF_Accuracy,'\n')
print('KNeighbours:',KNN_Accuracy,'\n')

Gradient Boosting : 0.9490909090909091 

Logistic Regression : 0.8636363636363636 

Random Forest : 0.9390909090909091 

KNeighbours: 0.889090909090909 



In [54]:
a=max(GB_Accuracy,LR_Accuracy,RF_Accuracy,KNN_Accuracy)
print("This is best result value",a)

This is best result value 0.9490909090909091


In [56]:
data=pd.read_csv("Employee_Attrition_Data.csv")

In [60]:
type(data)

pandas.core.frame.DataFrame

Im getting Gradient Boosting as Pefect model for predciting Churn Rate